"""
pg_schema.py — Schema PostgreSQL del modulo Servizi
====================================================
Crea il database `aib2026` (se assente) e tutte le tabelle con tipi corretti,
FOREIGN KEY e indici — le relazioni che in Access erano assenti.

Idempotente: CREATE TABLE/INDEX IF NOT EXISTS, rilanciabile senza danni.
Mappatura tipi: COUNTER → IDENTITY, BIT → BOOLEAN, LONGCHAR/MEMO → TEXT,
DATETIME → TIMESTAMP, DOUBLE → DOUBLE PRECISION.

  python pg_schema.py
Connessione: env DATABASE_URL (default postgresql://postgres:1234@localhost:5432/aib2026)
"""

import os
import psycopg2

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://postgres:1234@localhost:5432/aib2026")

DDL = """
CREATE TABLE IF NOT EXISTS qualifiche (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice      VARCHAR(10),
    descrizione VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS comandi (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice VARCHAR(20),
    nome   VARCHAR(100),
    attivo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS campagne_aib (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anno        INTEGER,
    data_inizio TIMESTAMP,
    data_fine   TIMESTAMP,
    descrizione TEXT,
    attiva      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS postazioni (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice           VARCHAR(20),
    nome             VARCHAR(100),
    note             TEXT,
    attiva           BOOLEAN NOT NULL DEFAULT TRUE,
    turni_multipli   BOOLEAN NOT NULL DEFAULT FALSE,
    slot_funzionario INTEGER,
    slot_tas2        INTEGER,
    slot_addetto     INTEGER
);

CREATE TABLE IF NOT EXISTS specialita (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice      VARCHAR(30),
    descrizione VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS funzioni_servizio (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice      VARCHAR(30),
    descrizione VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS personale (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricola    VARCHAR(20),
    qualifica_id INTEGER REFERENCES qualifiche(id),
    cognome      VARCHAR(100),
    nome         VARCHAR(100),
    telefono     VARCHAR(20),
    comando_id   INTEGER REFERENCES comandi(id),
    email        VARCHAR(150),
    attivo       BOOLEAN NOT NULL DEFAULT TRUE,
    note         TEXT
);

CREATE TABLE IF NOT EXISTS utenti (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(50),
    password_hash  VARCHAR(255),
    ruolo          VARCHAR(20),
    personale_id   INTEGER REFERENCES personale(id),
    comando_id     INTEGER REFERENCES comandi(id),
    attivo         BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_accesso TIMESTAMP
);

CREATE TABLE IF NOT EXISTS personale_specialita (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personale_id  INTEGER REFERENCES personale(id)  ON DELETE CASCADE,
    specialita_id INTEGER REFERENCES specialita(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS presenze (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campagna_id     INTEGER REFERENCES campagne_aib(id),
    personale_id    INTEGER REFERENCES personale(id),
    postazione_id   INTEGER REFERENCES postazioni(id),
    funzione_id     INTEGER REFERENCES funzioni_servizio(id),
    data_servizio   TIMESTAMP,
    orario_inizio   VARCHAR(5),
    orario_fine     VARCHAR(5),
    ore_totali      DOUBLE PRECISION,
    stato           VARCHAR(20),
    note_consuntivo TEXT,
    creato_da       INTEGER REFERENCES utenti(id),
    creato_il       TIMESTAMP,
    modificato_il   TIMESTAMP,
    fascia_oraria   VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS sessioni (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token     VARCHAR(64) NOT NULL,
    utente_id INTEGER NOT NULL REFERENCES utenti(id) ON DELETE CASCADE,
    scadenza  TIMESTAMP NOT NULL,
    creato_il TIMESTAMP
);

CREATE TABLE IF NOT EXISTS utenti_moduli (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id     INTEGER NOT NULL REFERENCES utenti(id) ON DELETE CASCADE,
    codice_modulo VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS report_templates (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(100),
    sorgente      VARCHAR(20),
    definizione   TEXT,
    creato_da     INTEGER REFERENCES utenti(id),
    creato_il     TIMESTAMP,
    aggiornato_il TIMESTAMP
);

-- ── Indici ──────────────────────────────────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS ux_sessioni_token        ON sessioni(token);
CREATE INDEX        IF NOT EXISTS ix_sessioni_utente       ON sessioni(utente_id);
-- username unico tra gli utenti ATTIVI (nei dati storici esiste un admin
-- duplicato disattivato: l'indice parziale lo tollera)
CREATE UNIQUE INDEX IF NOT EXISTS ux_utenti_username_attivi ON utenti(username) WHERE attivo;
CREATE INDEX        IF NOT EXISTS ix_presenze_campagna     ON presenze(campagna_id);
CREATE INDEX        IF NOT EXISTS ix_presenze_personale    ON presenze(personale_id);
CREATE INDEX        IF NOT EXISTS ix_presenze_postazione   ON presenze(postazione_id);
CREATE INDEX        IF NOT EXISTS ix_presenze_data         ON presenze(data_servizio);
CREATE INDEX        IF NOT EXISTS ix_personale_comando     ON personale(comando_id);
CREATE INDEX        IF NOT EXISTS ix_personale_cognome     ON personale(cognome, nome);
CREATE UNIQUE INDEX IF NOT EXISTS ux_personale_spec        ON personale_specialita(personale_id, specialita_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_utenti_moduli         ON utenti_moduli(utente_id, codice_modulo);
CREATE UNIQUE INDEX IF NOT EXISTS ux_postazioni_codice     ON postazioni(codice);
"""


def crea_database():
    """Crea il database di destinazione se non esiste (CREATE DATABASE
    non supporta IF NOT EXISTS, quindi si controlla pg_database)."""
    nome_db = DATABASE_URL.rsplit("/", 1)[1]
    url_postgres = DATABASE_URL.rsplit("/", 1)[0] + "/postgres"
    conn = psycopg2.connect(url_postgres)
    conn.autocommit = True   # CREATE DATABASE non può stare in transazione
    cur = conn.cursor()
    cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (nome_db,))
    if cur.fetchone():
        print(f"Database '{nome_db}' già esistente — skip.")
    else:
        cur.execute(f'CREATE DATABASE "{nome_db}" ENCODING \'UTF8\'')
        print(f"Database '{nome_db}' creato.")
    conn.close()


def crea_tabelle():
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()
    cur.execute(DDL)
    conn.commit()
    cur.execute("""
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = 'public' ORDER BY table_name
    """)
    print("Tabelle presenti:", ", ".join(r[0] for r in cur.fetchall()))
    conn.close()


if __name__ == "__main__":
    crea_database()
    crea_tabelle()
    print("Schema PostgreSQL pronto.")
